config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :users
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :tags, only: [:show, :new, :create, :destroy]
  resources :groups, only: [:index, :show, :new, :create]
  resources :memberships, only: [:create, :destroy]

  get "/games/add" => "games#add_index", as: :add_game_index
  get "/games/add/:api_id" => "games#add_show", as: :add_game_show
  post "/games/add" => "games#add_create", as: :add_game_create

  post "/games/:game_id/taggings/:id" => "taggings#create"
  delete "/games/:game_id/taggings/:id" => "taggings#destroy"

  resources :games do
  	resources :reviews
    resources :collections #, shallow: true

  end

  resources :friend_requests, only: [:create, :destroy, :update]

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to @group
    else
      redirect_to '/group/new'
    end
  end

  def show
    @group = Group.find(params[:id])
    @title = @group.name
    @group = @group.users
  end
  
  private
  def group_params
    params.require(:group).permit(:name)
  end

end

app/views/groups/index.html.erb
<h2>All Groups</h2>

<h4><%= link_to "Create a New Group!", new_group_path %></h4>

<br>

<% @groups.each do |group| %>
<ul class="list-group">
  <li class="list-group-item">
    <% if group_member?(session[:user_id], group.id) %>
    <span class="badge">Member</span>
    <% elsif current_user %>
      <span class="pull-right">
      <%= button_to 'Join Group', {:controller=>"memberships", :action=> "create", :user_id=>session[:user_id], :group_id=>group.id},:method=>:post, :class => 'btn btn-primary btn-sm' %>
      </span>
    <% end %>
      <%= link_to group.name, group_path(group) %>
  </li>
</ul>
<% end %>

app/views/groups/new.html.erb
<%= bootstrap_form_for(@group) do |f| %>
      <%= f.text_field :name %>
      <%= f.submit "Create Group" %>
<% end %>

app/views/groups/show.html.erb
<h2><%= @title %></h2>
<h4>Members</h4>

<% @group.each do |member| %>
<ul class="list-group">
  <li class="list-group-item">
      <%= link_to member.fullname, user_path(member) %>
  </li>
</ul>
<% end %>