config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :users
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :tags, only: [:show, :new, :create, :destroy]
  resources :groups, only: [:index, :show, :new, :create]
  resources :memberships, only: [:create, :destroy]

  get "/games/add" => "games#add_index", as: :add_game_index
  get "/games/add/:api_id" => "games#add_show", as: :add_game_show
  post "/games/add" => "games#add_create", as: :add_game_create

  post "/games/:game_id/taggings/:id" => "taggings#create"
  delete "/games/:game_id/taggings/:id" => "taggings#destroy"

  resources :games do
  	resources :reviews
    resources :collections #, shallow: true

  end

  resources :friend_requests, only: [:create, :destroy, :update]

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :firstname, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_secure_password
  has_many :collections
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :games, through: :collections
  has_many :reviews, foreign_key: :reviewer_id
  has_many :sent_requests, class_name: "FriendRequest", foreign_key: :sender_id
  has_many :received_requests, class_name: "FriendRequest", foreign_key: :recipient_id

  def friends
    all_friends= []
    self.sent_requests.each do |req|
      all_friends << User.find(req.recipient_id) if req.status == true
    end
    self.received_requests.each do |req|
      all_friends << User.find(req.sender_id) if req.status == true
    end
    all_friends
  end

  def is_admin?
    self.admin
  end

  def fullname
    self.firstname + " " + self.lastname
  end

  def get_collection(game_id)
    @collections = self.collections
    @collections.each do |col|
      p col
      if col.id == game_id
        return col
      else
        return false
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @people = User.all
    @users = []
    @people.each do |person| #this logic removes current_user from @users so user will not see him/herself from list of all users
      unless person.id == session[:user_id]
        @users << person
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      redirect_to '/users/new'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to articles_path
  end

  private
  def user_params
    params.require(:user).permit(:firstname, :lastname, :email, :password)
  end

end

app/views/users/_friends.html.erb
<% if session[:user_id] %>
  <h3>Friends</h3>
  <% if current_user.friends.count > 0 %>
    <ul class="no-list">
      <% current_user.friends.each do |friend| %>
        <li><a href="/users/<%= friend.id %>"><%= friend.firstname %> <%= friend.lastname %></a></li>

      <% end %>
    </ul>
    <% else %>
    <p><em>Link up with your friends to see their games.</em></p>
  <% end %>
  <%= button_to('Find Friends', users_path, :class => 'btn btn-purple btn-sm', :method => :get)  %>
<% end %>
  <% if current_user && current_user.groups.length > 0 %>
    <div id="groups">
      <h4>Groups</h4>
      <ul class="no-list margin-10">
      <% current_user.groups.each do |group| %>
        <li>
        <a href="/groups/<%= group.id %>"><%= group.name %></a>
      </li>
      <% end %>
    </ul>
    </div>
  <% end %>

app/views/users/index.html.erb
<h2>Find Your Friends</h2>


<% @users.each do |user| %>
<ul class="list-group">
  <li class="list-group-item">
    <% if current_friend?(user.id) %>
      <span class="badge">Friends</span>
    <% elsif request_sent?(user.id) %>
      <span class="badge">Request Pending</span>
    <% elsif request_received?(user.id)%>
      <span class="pull-right">
      <%= button_to 'Delete Request', {:controller=>"friend_requests", :action=> "destroy", :id=> user.id}, :method=>:delete, :class => 'btn btn-danger btn-sm' %>
      </span>
      <span class="pull-right">
      <%= button_to 'Accept Request', {:controller=>"friend_requests", :action=> "update", :id=>user.id}, :method=>:patch, :class => 'btn btn-success btn-sm' %>
      </span>
    <% else %>
      <span class="pull-right">
      <%= button_to 'Add Friend', {:controller=>"friend_requests", :action=> "create", :recipient_id=> user.id, :sender_id=>session[:user_id]}, :method=>:post, :class => 'btn btn-primary btn-sm' %>
      </span>
    <% end %>
      <%= link_to user.fullname, user_path(user) %>
  </li>
</ul>
<% end %>

app/views/users/new.html.erb
<%= bootstrap_form_for(@user) do |f| %>
      <%= f.text_field :firstname %>
      <%= f.text_field :lastname %>
      <%= f.email_field :email %>
      <%= f.password_field :password %>
      <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<% if @user.id == session[:user_id] %>
  <h3 class="text-center pad-15">Hey, <%= @user.firstname.upcase %></h3>


  <div class="collection">
    <h4 class="pad-15 text-center">Your Game Collection</h4>
    <% if @user.games.count > 0 %>
    <ul class="no-list">
      <% @user.games.each do |game| %>
        <li class="text-center pad-10"><a href="/games/<%= game.id %>"><%= game.name %><img src="<%= game.thumbnail_url %>" class="tiny-pic"/></a></li>
      <% end %>
    </ul>

    <div class="friends-circle text-center">
      <h4 class="pad-15 text-center">Games in your Circle</h4>
      <% @user.friends.each do |friend| %>

      <div class="friend-games">

        <p class="pad-5 left-20"><strong><%= friend.firstname %></strong></p>
          <% if friend.games.count > 0 %>
            <ul class="no-list">
              <% friend.games.each do |game| %>
              <li class="pad-10"><a href="/games/<%= game.id %>"><%= game.name %><img src="<%= game.thumbnail_url %>" class="tiny-pic"/></a></li>
              <% end %>
            </ul>
          <% else %>
            <p><em>No games yet</em></p>
          <% end %>

        </div>
      <% end %>
    </div>

    <% else %>
      <p class="pad-15 text-center"><em>You don't have any games in your collection. <%= link_to 'Add some games!', games_path %></em></p>
    <% end %>
  </div>

<% else %>
  <h3 class="text-center pad-15"><%= @user.firstname.upcase %></h3>

  <div class="collection">
    <h4 class="pad-15 text-center">Game Collection</h4>
    <% if @user.games.count > 0 %>
    <ul class="no-list">
      <% @user.games.each do |game| %>
        <li class="text-center pad-10"><a href="/games/<%= game.id %>"><%= game.name %><img src="<%= game.thumbnail_url %>" class="tiny-pic"/></a></li>
      <% end %>
    </ul>

    <% else %>
      <p class="text-center"><em>No games yet</em></p>
    <% end %>
  </div>

<% end %>