config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :users
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :tags, only: [:show, :new, :create, :destroy]
  resources :groups, only: [:index, :show, :new, :create]
  resources :memberships, only: [:create, :destroy]

  get "/games/add" => "games#add_index", as: :add_game_index
  get "/games/add/:api_id" => "games#add_show", as: :add_game_show
  post "/games/add" => "games#add_create", as: :add_game_create

  post "/games/:game_id/taggings/:id" => "taggings#create"
  delete "/games/:game_id/taggings/:id" => "taggings#destroy"

  resources :games do
  	resources :reviews
    resources :collections #, shallow: true

  end

  resources :friend_requests, only: [:create, :destroy, :update]

end

app/models/game.rb
class Game < ActiveRecord::Base

  searchkick

  has_many :collections
  has_many :users, through: :collections
  has_many :reviews
  has_many :taggings
  has_many :tags, through: :taggings

  validates :api_id, uniqueness: true

  def short_description
    short_string = self.description.slice(0..200) + ". . . "
  end

  def average_score
    total = 0
    self.reviews.each do |review|
      total += review.rating
    end
    return total/self.reviews.length if self.reviews.length != 0
    return 0
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  helper_method :sort_column, :sort_direction
  include ApplicationHelper

  def index
    if params[:sort] == "popularity"
      return @games = Game.all.sort_by {|game| game.average_score}.reverse
    end
      @games = Game.order(sort_column + " " + sort_direction)
    if params[:name].present?
      @games = Game.search(params[:name])
    end
  end

  def show
    @game = Game.find(params[:id])
    @reviews = @game.reviews.order('created_at DESC')
    if params[:name].present?
      search_words = fix_search_words(params[:name])
      parse_xml_titles("http://www.boardgamegeek.com/xmlapi/search?search=#{search_words}")
    end
  end

  def add_index
    if params[:name].present?
      search_words = fix_search_words(params[:name])
      @game_data = parse_xml_titles("http://www.boardgamegeek.com/xmlapi/search?search=#{search_words}")
    end
  end

  def add_show
    @game_data = parse_game_data(params[:api_id])
    flash[:game_data] = @game_data
  end

  def add_create
    if flash[:game_data]
      game = Game.new(flash[:game_data])
      if game.save
        redirect_to games_path
      else
        @game_data = flash[:game_data]
        render
      end
    end
  end

  private 

  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    params[:direction] || "asc"
  end

end

app/views/games/add.html.erb
<div class="game-detail">
  <img src=<%= @game_data[:image_url] %> height="500" width="500" class="game-pic">
  <h3><%= @game_data[:name] %></h3>
  <p><strong>Min Players: </strong><%= @game_data[:min_players] %></p>
  <p><strong>Max Players: </strong><%= @game_data[:max_players] %></p>
  <p><strong>Playing Time: </strong><%= @game_data[:playing_time] %> minutes</p>
  <p><strong>Description:</strong> <%= @game_data[:description] %></p>
</div>
<div class="pad-15">
  <%= form_tag(add_game_create_path(@game_data) do %>
    <%= submit_tag("Add to collection") %>
  <% end %>
</div>

app/views/games/add_index.html.erb
<div class = "container pad-15">
  <br>
  <%= form_tag("/games/add", method: "get") do %>
  <%= text_field_tag :name, nil, placeholder: "Search the Internet" %>
  <%= submit_tag "Search", class: "btn btn-purple" %>
  <% end %>
  <br>
    <% if @game_data != nil %>
    <% @game_data.each do |game| %>
      <li>
        <a href="/games/add/<%= game[:id] %>"><%= game[:name] %></a>
      </li>
    <% end %>
    <% else %>
      <p>No results</p>
  <% end %>
</div>

app/views/games/add_show.html.erb
<div class="game-detail">
  <img src=<%= @game_data[:image_url] %> height="500" width="500" class="game-pic">
  <h3><%= @game_data[:name] %></h3>
  <p><strong>Min Players: </strong><%= @game_data[:min_players] %></p>
  <p><strong>Max Players: </strong><%= @game_data[:max_players] %></p>
  <p><strong>Playing Time: </strong><%= @game_data[:playing_time] %> minutes</p>
  <p><strong>Description:</strong> <%= @game_data[:description] %></p>
</div>
<div class="pad-15">
  <%= form_tag("/games/add", method: "post") do %>
    <%= submit_tag "Add to Database", class: "btn btn-purple" %>
  <% end %>
</div>

app/views/games/index.html.erb
  <div class="well inline-headers">
    <h6>Sort Games By:</h6>
    <h6><%= link_to "Most Popular", :sort => "popularity" %></h6>
    <h6><%= sortable "name" %></h6>
    <h6><%= sortable "created_at" %></h6>
  </div>
<ul class="no-list">
  <br>
  <% if !@games.empty? %>
    <% @games.each do |game| %>
      <li>
        <a href ="games/<%= game.id %>"> <img src=<%= game.thumbnail_url %> style="width:35px;height:35px;"></a>
        <a href="games/<%= game.id %>"><%= game.name %></a>
        <p><%= game.short_description %></p>
      </li>
    <% end %>
    <% else %>
      <p>No results</p>
  <% end %>
</ul>
<div class="pad-15">
  <%= form_tag("/games/add", method: "get") do %>
    <%= submit_tag "Search for New Games", class: "btn btn-purple" %>
  <% end %>
</div>

app/views/games/show.html.erb
<div class="game-detail">
  <img src=<%= @game.image_url %> height="500" width="500" class="game-pic">
  <h3><%= "#{@game.name}" %></h3>
  <p><strong>Rating: </strong><%= @game.average_score %></p> <!-- PLACEHOLDER -->
  <p><strong>Min Players: </strong><%= @game.min_players %></p>
  <p><strong>Max Players: </strong><%= @game.max_players %></p>
  <p><strong>Playing Time: </strong><%= @game.playing_time %> minutes</p>
  <p><strong>Description:</strong> <%= @game.description %></p>

  <% if current_user %>
    <% unless current_user.games.include?(@game) %>
      <div class="pad-15">
        <%= form_tag(game_collections_path(@game)) do %>
          <%= submit_tag "Add to collection", class: "btn btn-purple" %>
        <% end %>
      </div>
    <% else %>
      <div class="text-bkg-antique">
        <p class="pad-10 margin-no"><em>This game is in your collection.</em></p>
        <!-- form action path is not working below need to get correct collection for game && user -->
        <form action="<%= game_collection_path(@game, Collection.find_by(user_id: current_user.id, game_id: @game.id) ) %>" method="POST" id="form-group remove-game-col" class="text-center">
          <input type="submit" value="Remove" class="btn btn-xs btn-default margin-b-10">
          <input type="hidden" name="_method" value="delete">
          <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
        </form>
      </div>

    <% end %>
  <% end %>

</div>


<section class="reviews-section collection col-md-12 margin-10">

  <% if current_user %>
    <div class="col-md-8 col-md-offset-2">
      <%= link_to 'Leave a review', new_game_review_path(@game), :remote => true, :id => "new_review_link", :class => "btn btn-sm btn-block btn-purple" %>
    </div>
    <div class="spacer"> </div>
  <% end %>

  <div id="reviews">
    <% if @game.reviews.length > 0 %>
      <% @reviews.each do |review| %>
        <%= render "reviews/review", :review => review %>
      <% end %>
    <% end %>
  </div>

  <!-- empty div to add bottom margin  -->
  <div class="col-md-12">
    <div class="spacer"> </div>
  </div>
</section>