config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :users
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :tags, only: [:show, :new, :create, :destroy]
  resources :groups, only: [:index, :show, :new, :create]
  resources :memberships, only: [:create, :destroy]

  get "/games/add" => "games#add_index", as: :add_game_index
  get "/games/add/:api_id" => "games#add_show", as: :add_game_show
  post "/games/add" => "games#add_create", as: :add_game_create

  post "/games/:game_id/taggings/:id" => "taggings#create"
  delete "/games/:game_id/taggings/:id" => "taggings#destroy"

  resources :games do
  	resources :reviews
    resources :collections #, shallow: true

  end

  resources :friend_requests, only: [:create, :destroy, :update]

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
 
	before_action :find_review, only: [:show]
	def new
		@review = Review.new
		@game = Game.find(params[:game_id])
		respond_to do |format|
			format.html # new.html.erb
			format.json { render json: @review }
			format.js
		end
	end

	def edit
		@review = Review.find(params[:id])
		@game = Game.find(params[:game_id])
	end

	def update
	  @game = Game.find(params[:game_id])
      @review = Review.find(params[:id])
      if @review.update(params_review)
        redirect_to @game
      else
        @errors = @review.errors.full_messages
        render 'new'
      end
    end

	def show
		@rewiew = Review.find(params[:id])
	end

	def create
	  @review = current_user.reviews.build(params_review)
	  @game = Game.find(params[:game_id])
	  @review.game = @game
	  respond_to do |format|
	    if @review.save
	      format.html { redirect_to @game }
	      format.json { render json: @review, status: :created, location: @game }
	      format.js

	    else
	      format.html { render action: "new" }
	      format.json { render json: @review.errors, status: :unprocessable_entity }
	      format.js
	    end
	  end
	end


	def destroy
    @review = Review.find(params[:id])
    @review.destroy
    @game = Game.find(params[:game_id])

    respond_to do |format|
      format.html { redirect_to @game }
      format.json { head :no_content }
      format.js
    end
  end

	private

	def params_review
		params.require(:review).permit(:rating, :description)
	end

	def find_review
		@review = Review.find(params[:id])
	end


end

app/views/reviews/_form.html.erb
<%= simple_form_for([@game, @game.reviews.build], remote: true, id: 'new_review', defaults: { input_html: { class: 'default_class' } }) do |f| %>
	<h2 class="purple">Leave a review</h2>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



	<%= f.label(:rating, "★") %>
	<%= f.radio_button(:rating, 1) %>
	<%= f.label(:rating, "★") %>
	<%= f.radio_button(:rating, 2) %>
	<%= f.label(:rating, "★") %>
	<%= f.radio_button(:rating, 3) %>
	<%= f.label(:rating, "★") %>
	<%= f.radio_button(:rating, 4) %>
	<%= f.label(:rating, "★") %>
	<%= f.radio_button(:rating, 5) %><span><b> Rate!</b></span><br />
	<%= f.text_area :description, class: 'white-pink' %><br />

  <%= f.submit class: 'btn btn-sm btn-purple' %>

<% end %>

app/views/reviews/_review.html.erb
<article id="review_<%= review.id %>" class="round">
	<span class="right"><em>created <%= time_ago_in_words(review.created_at) %> ago</em></span>

	<img style="width:3em;" class="cow" src="http://jaredsilver.name/cows/cow2.png">

	<% if  review.reviewer %>
		<span><strong><em><%= review.reviewer.firstname %></strong></em> rated game:</span>
		<span class="purple"> <strong><%= review.rating %> </strong></span>
	<% end %>

	<center>
		<p class="purple"><%= review.description %></p></center>
	<span class="right">

	<% if current_user %>
		<%= link_to 'Edit', edit_game_review_path(review.game,review) %> |

		<% if manageable(review.reviewer.id) %>
			<%= link_to 'Destroy', game_review_path(review.game,review), method: :delete, data: { confirm: 'Are you sure?' }, :remote => true %>
		<% end %>
	<% end %>

	<span>
</article>

app/views/reviews/create.js.erb
<% if @game.errors.count == 0 %>

	$('#new_review').remove();
	$('#new_review_link').show();
	$('#reviews').prepend('<%= j render("review", :review => @review) %>');

<% else %>

	$('.new_review').remove();
	$('#new_review_link').after('<%= j render("form") %>');

<% end %>

app/views/reviews/destroy.js.erb
$('#review_<%= @review.id %>').remove();

app/views/reviews/edit.html.erb
<center>
	<%= simple_form_for([@game,@review], :html => {:class => "form-horizontal center"}) do |f| %>
		<h2 class="purple">Update a review</h2>
		<%= f.text_area :description, class: 'white-pink'  %><br />
		<div class="form-actions">
		<%= f.submit class: 'btn btn-purple smaller' %>
		</div>
	<% end %>
<center>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', @game %>

app/views/reviews/new.js.erb
$('#new_review_link').hide().after('<%= j render("form") %>');

app/views/reviews/show.html.erb
rewiew